#!/usr/bin/env python3
"""Generate the tape-reel disc image used by the reel player skin.

76x76 RGB565A8 LVGL images: a mint disc with a dark rim and three 70-degree
windows (radius 13..31) cut out, so the tape pack drawn behind it shows through.
The disc has 3-fold symmetry, so FRAMES pre-rotated frames covering 0..120 degrees
are stored in flash; the firmware animates by switching frames, which needs no
runtime transform buffers. Rendered at 4x and downsampled for anti-aliasing.
Requires Pillow.
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets/images/bp_reel_disc.c"
SIZE, SS = 76, 4
FRAMES = 24             # 5 degrees per frame over the 120-degree symmetry period
FILL = (0xEF, 0xFF, 0xF5, 255)
INK = (0x09, 0x21, 0x13, 255)
CLEAR = (0, 0, 0, 0)
R_OUT, R_IN, R_WIN = 37.2, 13.0, 31.0   # disc radius (inside the rim stroke), window radii
STROKE = 1.5


def render(angle: float) -> Image.Image:
    n = SIZE * SS
    c = n / 2
    img = Image.new("RGBA", (n, n), CLEAR)
    d = ImageDraw.Draw(img)
    w = round(STROKE * SS)

    def box(r):
        return [c - r * SS, c - r * SS, c + r * SS, c + r * SS]

    d.ellipse(box(R_OUT), fill=FILL, outline=INK, width=w)
    for k in range(3):
        a0 = -90 + k * 120 - 35 + angle
        a1 = a0 + 70
        d.pieslice(box(R_WIN), a0, a1, fill=CLEAR, outline=INK, width=w)   # window to r2
        d.pieslice(box(R_IN), a0 - 2, a1 + 2, fill=FILL)                  # restore hub area
        d.arc(box(R_IN), a0, a1, fill=INK, width=w)                        # window inner edge
    return img.resize((SIZE, SIZE), Image.LANCZOS)


def to_rgb565a8(img: Image.Image) -> tuple[bytes, bytes]:
    color, alpha = bytearray(), bytearray()
    raw = img.tobytes()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i:i + 4]
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        color += bytes((v & 0xFF, v >> 8))   # little-endian RGB565 (LVGL native)
        alpha.append(a)
    return bytes(color), bytes(alpha)


def main() -> None:
    lines = ["// Generated by tools/generate_reel_disc.py. Do not edit.", '#include "lvgl.h"', ""]
    total = 0
    for f in range(FRAMES):
        color, alpha = to_rgb565a8(render(f * 120.0 / FRAMES))
        data = color + alpha
        total += len(data)
        rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 24]) for i in range(0, len(data), 24)]
        lines.append(f"static const uint8_t frame_{f}[{len(data)}] = {{\n    " + ",\n    ".join(rows) + "\n};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t bp_reel_disc[{FRAMES}] = {{")
    for f in range(FRAMES):
        lines.append("    {.header.magic = LV_IMAGE_HEADER_MAGIC, .header.cf = LV_COLOR_FORMAT_RGB565A8,"
                     f" .header.w = {SIZE}, .header.h = {SIZE}, .header.stride = {SIZE * 2},"
                     f" .data_size = sizeof(frame_{f}), .data = frame_{f}}},")
    lines.append("};")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"bp_reel_disc: {FRAMES} frames {SIZE}x{SIZE} RGB565A8, {total} bytes -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
