#!/usr/bin/env python3
"""Encode the Baidu app credentials so the firmware image holds no plaintext copy.

Reads BP_BAIDU_APPKEY / BP_BAIDU_SECRET from a keys header and writes a C header
with two byte arrays per value: data[i] = plain[i] ^ mask[i] ^ (i * 0x5B + 0x3D).
The mask is derived deterministically (SHA-256 of a salt, the value name and a
counter) so identical inputs give identical, reproducible firmware.

This only defeats static string scanning (`strings`, hex search). The decoder and
both arrays ship in the firmware, so it is obfuscation, not protection.
Never prints the credential values.
"""
import argparse
import hashlib
import pathlib
import re
import sys

SALT = b"baidupan-pocket-player/keys/v1"
NAMES = ("BP_BAIDU_APPKEY", "BP_BAIDU_SECRET")


def read_keys(path: pathlib.Path) -> dict[str, bytes]:
    text = path.read_text(encoding="utf-8")
    keys = {}
    for name in NAMES:
        match = re.search(rf'#define\s+{name}\s+"([^"\\]*)"', text)
        if not match:
            sys.exit(f"{path}: missing {name}")
        keys[name] = match.group(1).encode()
    return keys


def mask(name: str, length: int) -> bytes:
    out = b""
    counter = 0
    while len(out) < length:
        out += hashlib.sha256(SALT + name.encode() + counter.to_bytes(4, "little")).digest()
        counter += 1
    return out[:length]


def encode(name: str, plain: bytes) -> tuple[bytes, bytes]:
    m = mask(name, len(plain))
    data = bytes(p ^ k ^ ((i * 0x5B + 0x3D) & 0xFF) for i, (p, k) in enumerate(zip(plain, m)))
    return data, m


def c_array(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data) or "0x00"
    return f"static const volatile uint8_t {name}[] = {{{body}}};\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--in", dest="src", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    keys = read_keys(args.src)
    placeholder = any(v.startswith(b"REPLACE_WITH_") for v in keys.values())
    lines = [
        "// Generated by tools/obfuscate_keys.py. Do not edit or commit.\n",
        "#pragma once\n#include <stdint.h>\n\n",
        f"#define BP_KEYS_PLACEHOLDER {1 if placeholder else 0}\n",
    ]
    for name in NAMES:
        short = name.removeprefix("BP_BAIDU_").lower()
        data, m = encode(name, keys[name])
        lines.append(f"#define BP_KEY_{short.upper()}_LEN {len(data)}\n")
        lines.append(c_array(f"bp_key_{short}_data", data))
        lines.append(c_array(f"bp_key_{short}_mask", m))
    content = "".join(lines)
    # Write only on change so the build does not recompile needlessly.
    if not args.out.exists() or args.out.read_text() != content:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(content)
    print(f"obfuscate_keys: encoded {len(NAMES)} values from {args.src.name}"
          f"{' (placeholders)' if placeholder else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
